# -*- mode: ruby -*-
# vi: set ft=ruby :

# Designates veribles with ip for the VMs
CONTROL_IP = "192.168.56.10"
LOADBARING_IP = "192.168.56.11"
WEBSERVER1_IP = "192.168.56.12"
WEBSERVER2_IP = "192.168.56.13"
DATABASE_IP = "192.168.56.14"
STREAMING_IP = "192.168.56.15"

# Designates veribles for RAM and CPUs
RAM = "1024"
CPUs = "1"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  
  # Control vm 
  config.vm.define "control" do |ctrl|
    ctrl.vm.hostname = "control"
    ctrl.vm.network "private_network", ip: CONTROL_IP
    ctrl.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    ctrl.vm.provision "shell", inline: <<-SHELL

    # Automatilcy uppdates the vm on start
    apt-get update

    # Installs Ansible and Github-git on boot up
    apt-get install -y ansible git

    # Clone repo at boot up
    git clone -b 07-added-inventory.ini https://github.com/A-Hagman/ITS25-School-project-Load-balanced-Video-Streaming-Server.git /home/vagrant/project

    chmod 755 /home/vagrant/project
    
    sudo -u vagrant ssh-keygen -t ed25519 -f /home/vagrant/.ssh/id_ed25519 -N "" -C "ansible-kontroll"

  
    cp /home/vagrant/.ssh/id_ed25519.pub /vagrant/ansible_id_ed25519.pub


        echo -e "\e[32m=================================\e[0m"
        echo -e "\e[32m         Control Online          \e[0m"
        echo -e "\e[32m=================================\e[0m"
      SHELL
  end 
  
  # Loadbaring vm
  config.vm.define "loadbaring" do |lb|
    lb.vm.hostname = "loadbaring"
    lb.vm.network "private_network", ip: LOADBARING_IP
    lb.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    lb.vm.provision "shell", inline: <<-SHELL
    # Automatilcy uppdates the vm on start
    apt-get update

    while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
      echo "Väntar på publik nyckel..."
      sleep 3
    done

    mkdir -p /home/vagrant/.ssh
    cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant  /home/vagrant/.ssh

        echo -e "\e[32m=================================\e[0m"
        echo -e "\e[32m      Loadbaring Online          \e[0m"
        echo -e "\e[32m=================================\e[0m"
      SHELL
  end 

  # Webbserver 1
  config.vm.define "webserver1" do |web1|
    web1.vm.hostname = "webserver1"
    web1.vm.network "private_network", ip: WEBSERVER1_IP
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    web1.vm.provision "shell", inline: <<-SHELL
    # Automatilcy uppdates the vm on start
    apt-get update

    while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
      echo "Väntar på publik nyckel..."
      sleep 3
    done

    mkdir -p /home/vagrant/.ssh
    cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant  /home/vagrant/.ssh

      echo -e "\e[32m=================================\e[0m"
      echo -e "\e[32m       Webbserver1 Online        \e[0m"
      echo -e "\e[32m=================================\e[0m"
    SHELL
  end

  # Webbserver 2
  config.vm.define "webserver2" do |web2|
    web2.vm.hostname = "webserver2"
    web2.vm.network "private_network", ip: WEBSERVER2_IP
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = RAM 
      vb.cpus = CPUs
    end
    web2.vm.provision "shell", inline: <<-SHELL
    # Automatilcy uppdates the vm on start
    apt-get update

    while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
      echo "Väntar på publik nyckel..."
      sleep 3
    done

    mkdir -p /home/vagrant/.ssh
    cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant  /home/vagrant/.ssh

      echo -e "\e[32m=================================\e[0m"
      echo -e "\e[32m       Webbserver2 Online        \e[0m"
      echo -e "\e[32m=================================\e[0m"
    SHELL
  end
  
  # Database vm
  config.vm.define "database" do |db|
    db.vm.hostname = "database"
    db.vm.network "private_network", ip: DATABASE_IP
    db.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    db.vm.provision "shell", inline: <<-SHELL
      # Automatilcy uppdates the vm on start
      apt-get update

      while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
        echo "Väntar på publik nyckel..."
        sleep 3
      done

      mkdir -p /home/vagrant/.ssh
      cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant  /home/vagrant/.ssh

        echo -e "\e[32m=================================\e[0m"
        echo -e "\e[32m        Database Online          \e[0m"
        echo -e "\e[32m=================================\e[0m"
      SHELL
  end 

  # Streaming vm
  config.vm.define "streaming" do |str|
    str.vm.hostname = "streaming"
    str.vm.network "private_network", ip: STREAMING_IP
    str.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    str.vm.provision "shell", inline: <<-SHELL
      # Automatilcy uppdates the vm on start
      apt-get update

      while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
        echo "Väntar på publik nyckel..."
        sleep 3
      done

      mkdir -p /home/vagrant/.ssh
      cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant  /home/vagrant/.ssh

        echo -e "\e[32m=================================\e[0m"
        echo -e "\e[32m       Streaming Online          \e[0m"
        echo -e "\e[32m=================================\e[0m"
      SHELL
  end 

end
