# -*- mode: ruby -*-
# vi: set ft=ruby :

# Designates variables with ip for the VMs
CONTROL_IP = "192.168.56.10"
LOADBALANCER_IP = "192.168.56.11"
WEBSERVER1_IP = "192.168.56.12"
WEBSERVER2_IP = "192.168.56.13"
DATABASE_IP = "192.168.56.14"
STREAMING_IP = "192.168.56.15"

# Designates variables for RAM and CPUs
RAM = "1024"
CPUs = "1"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  
  # Control VM
  config.vm.define "control" do |ctrl|
    ctrl.vm.hostname = "control"
    ctrl.vm.network "private_network", ip: CONTROL_IP
    ctrl.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    ctrl.vm.provision "shell", inline: <<-SHELL

    # Automatically updates the VM on start
    apt-get update

    # Installs Ansible and Github-git on boot up
    apt-get install -y ansible git

    # Clone repo at boot up
    git clone -b 13-Clean-up https://github.com/A-Hagman/ITS25-School-project-Load-balanced-Video-Streaming-Server.git /home/vagrant/project

    chmod 755 /home/vagrant/project
    # Gives access to verify-script
    chmod +x /home/vagrant/project/ansible/verify.sh
    
    sudo -u vagrant ssh-keygen -t ed25519 -f /home/vagrant/.ssh/id_ed25519 -N "" -C "ansible-kontroll"

  
    cp /home/vagrant/.ssh/id_ed25519.pub /vagrant/ansible_id_ed25519.pub

    if [ -f /vagrant/secrets.yml ]; then
      cp /vagrant/secrets.yml /home/vagrant/project/ansible/vars/secrets.yml
      echo "secrets.yml copied"
    fi

      echo -e "\e[32m=================================\e[0m"
      echo -e "\e[32m         Control Online          \e[0m"
      echo -e "\e[32m=================================\e[0m"
    SHELL
  end 
  
  # Loadbalancer VM
  config.vm.define "loadbalancer" do |lb|
    lb.vm.hostname = "loadbalancer"
    lb.vm.network "private_network", ip: LOADBALANCER_IP
    lb.vm.network "forwarded_port", guest: 80, host: 8080
    lb.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    lb.vm.provision "shell", inline: <<-SHELL
    # Automatically updates the VM on start
    apt-get update

    while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
      echo "Waiting for public key.."
      sleep 3
    done

    mkdir -p /home/vagrant/.ssh
    cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant  /home/vagrant/.ssh

        echo -e "\e[32m=================================\e[0m"
        echo -e "\e[32m      Loadbalancer Online        \e[0m"
        echo -e "\e[32m=================================\e[0m"
      SHELL
  end 

  # Webbserver 1
  config.vm.define "webserver1" do |web1|
    web1.vm.hostname = "webserver1"
    web1.vm.network "private_network", ip: WEBSERVER1_IP
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    web1.vm.provision "shell", inline: <<-SHELL
    # Automatically updates the VM on start
    apt-get update

    while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
      echo "Waiting for public key.."
      sleep 3
    done

    mkdir -p /home/vagrant/.ssh
    cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant  /home/vagrant/.ssh

      echo -e "\e[32m=================================\e[0m"
      echo -e "\e[32m       Webbserver 1 Online       \e[0m"
      echo -e "\e[32m=================================\e[0m"
    SHELL
  end

  # Webbserver 2
  config.vm.define "webserver2" do |web2|
    web2.vm.hostname = "webserver2"
    web2.vm.network "private_network", ip: WEBSERVER2_IP
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = RAM 
      vb.cpus = CPUs
    end
    web2.vm.provision "shell", inline: <<-SHELL
    # Automatically updates the VM on start
    apt-get update

    while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
      echo "Waiting for public key.."
      sleep 3
    done

    mkdir -p /home/vagrant/.ssh
    cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
    chmod 700 /home/vagrant/.ssh
    chmod 600 /home/vagrant/.ssh/authorized_keys
    chown -R vagrant:vagrant  /home/vagrant/.ssh

      echo -e "\e[32m=================================\e[0m"
      echo -e "\e[32m       Webbserver 2 Online       \e[0m"
      echo -e "\e[32m=================================\e[0m"
    SHELL
  end
  
  # Database VM
  config.vm.define "database" do |db|
    db.vm.hostname = "database"
    db.vm.network "private_network", ip: DATABASE_IP
    db.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    db.vm.provision "shell", inline: <<-SHELL
      # Automatically updates the VM on start
      apt-get update

      while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
        echo "Waiting for public key.."
        sleep 3
      done

      mkdir -p /home/vagrant/.ssh
      cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant  /home/vagrant/.ssh

        echo -e "\e[32m=================================\e[0m"
        echo -e "\e[32m        Database Online          \e[0m"
        echo -e "\e[32m=================================\e[0m"
      SHELL
  end 

  # Streaming VM
  config.vm.define "streaming" do |str|
    str.vm.hostname = "streaming"
    str.vm.network "private_network", ip: STREAMING_IP
    str.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus = CPUs
    end
    str.vm.provision "shell", inline: <<-SHELL
      # Automatically updates the VM on start
      apt-get update

      while [ ! -f /vagrant/ansible_id_ed25519.pub ]; do
        echo "Waiting for public key.."
        sleep 3
      done

      mkdir -p /home/vagrant/.ssh
      cat /vagrant/ansible_id_ed25519.pub >> /home/vagrant/.ssh/authorized_keys
      chmod 700 /home/vagrant/.ssh
      chmod 600 /home/vagrant/.ssh/authorized_keys
      chown -R vagrant:vagrant  /home/vagrant/.ssh

      # Creates video directory and copy video file if it exists
      mkdir -p /var/www/videos
      if [ -f /vagrant/nitflix.mp4 ]; then
        cp /vagrant/nitflix.mp4 /var/www/videos/
        chown www-data:www-data /var/www/videos/nitflix.mp4
        chmod 644 /var/www/videos/nitflix.mp4
        echo "Video file copied"
      else
        echo "Warning: nitflix.mp4 not found in /vagrant/"
      fi

        echo -e "\e[32m=================================\e[0m"
        echo -e "\e[32m       Streaming Online          \e[0m"
        echo -e "\e[32m=================================\e[0m"
      SHELL
  end 

end
