#kopplar inventory till roller och tasks
- name: Configure loadbalancer
  hosts: loadbalancer
  become: yes
  vars_files:
    - vars/vars.yml 
  roles:
    - loadbalancer

#Lägg till databaskommandon här. Måste vara före webbservrar

- name: Configure webbservers
  hosts: webservers
  become: yes
  roles:
    - webservers