#kopplar inventory till roller och tasks
- name: Configure database
  hosts: database
  become: yes
  vars_files:
    - vars/vars.yml
    - vars/secrets.yml
  roles:
    - database

- name: Configure webbservers
  hosts: webservers
  become: yes
  vars_files:
    - vars/vars.yml
    - vars/secrets.yml
  roles:
    - webservers

- name: Configure loadbalancer
  hosts: loadbalancer
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - loadbalancer

- name: Configure streaming
  hosts: streaming
  become: yes
  roles:
    - streaming